server:
  port: 9090

spring:
  mvc:
    pathmatch:
      matching-strategy:
        ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wrr?serverTimezone=GMT%2b8
    username: root
    password: rlr011203

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

